### ISSUE TITLE
incorrect result for hierseg on zero data with family=poisson

### ISSUE THREAD

**Issue by tdhock** [Lucas-Prates/blockcpd#5]
hi @Lucas-Prates I expected that when I use lambda=0 then I should get the maximum number of changepoints. However when the data sequence contains a zero I observe less than the maximum number of changes. For example
```
> blockcpd::fit_blockcpd(t(matrix(0:3)), method="hierseg", family="poisson", lambda=0)$changepoints
[1] 2 3
```
In this case there are four data points so I expected a change after each one, but there is a missing changepoint after data point 1. Is this a bug?

**Comment by Lucas-Prates** [comment]
Hi! At first glance, there is a bug in it, but it is also a choice of definition. If we allow to segment blocks that only contain zero values, then we would estimate the rate parameter as zero, which could be unwanted since the Poisson parameter is usually assumed to be greater than 0. However, extending it to have the rate parameter as 0 is possible, and is the convention I prefer for now.

Note that, when lambda = 0, you do not necessarily have to output the maximum number of change-points. For instance, if your dataset is c(0, 0, 1, 2, 3), the model with change-points c(1, 2, 3, 4) and c(2, 3, 4) are identical, so we can choose which to return.

The bug was related to 0*log(0) computations, it should be fixed in the latest commit.

Thank you again.

**Comment by tdhock** [comment]
great thanks!
```r
> devtools::install_github("Lucas-Prates/blockcpd@46e7cd71e6a1c92c2649025fe0775dc9e25e6376")
Skipping install of 'blockcpd' from a github remote, the SHA1 (46e7cd71) has not changed since last install.
  Use `force = TRUE` to force installation
> blockcpd::fit_blockcpd(t(matrix(0:3)), method="hierseg", family="poisson", lambda=0)$changepoints
[1] 1 2 3
```
